tasks:
  - name: localnet start
    command: >
      gp sync-await algokit-install && 
      /workspace/algokit localnet start 
      && exit 
  - name: install algokit
    command: > 
      pip install pipx && 
      PIPX_HOME=/workspace/ PIPX_BIN_DIR=$PIPX_HOME pipx install algokit &&
      gp sync-done algokit-install &&
      exit
  - name: update PATH
    command: >
      PATH=$PATH:/workspace &&
      exit
vscode:
  extensions:
    - ms-python.python
ports:
  - name: algod
    port: 4001
    visibility: public
    onOpen: ignore
  - name: indexer
    port: 8980
    visibility: public
    onOpen: ignore
  - name: postgres
    port: 5432
    onOpen: ignore
  - name: kmd
    port: 4002
    visibility: public
    onOpen: ignore
  - name: debug port
    port: 9392
    onOpen: ignore
    visibility: public
  - name: webpack
    port: 8080
    visibility: public
    onOpen: ignore
